version: '3.8'

services:
  backend:
    image: denoland/deno:alpine-1.42.1
    container_name: veeda_backend
    working_dir: /app/backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - deno_cache:/deno-dir
    env_file:
      - ./backend/.env
    command: ["deno", "task", "dev"]
    # depends_on:
    #   - db  # Uncomment if you add a database service

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: dev
    container_name: veeda_web
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      # Avoid overwriting node_modules in the container with local ones
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Required for HMR in Docker
      - VITE_BACKEND_URL=http://backend:8000 # Allows web to call backend via service name
    depends_on:
      - backend

volumes:
  deno_cache: 