# backend/wrangler.toml

# A unique name for your Worker. This will form part of its URL.
name = "veeda-backend"

# The main entry point for your Worker code.
main = "main.ts"

# Specifies the compatibility date for the Workers runtime.
compatibility_date = "2024-04-05"

# Enable Deno Compatibility
compatibility_flags = [ "deno", "nodejs_compat" ]

# Top-level vars (copy these to env.production.vars as well)
[vars]
ENVIRONMENT = "production"

# Production environment
[env.production]
name = "veeda-backend-worker"

# Copy vars here to fix the warning
[env.production.vars]
ENVIRONMENT = "production"

[observability.logs]
enabled = true
