# backend/wrangler.toml

# A unique name for your Worker. This will form part of its URL.
name = "veeda-backend" # This seems fine

# The main entry point for your Worker code. Pointing to your modified main.ts
main = "main.ts"

# Specifies the compatibility date for the Workers runtime.
compatibility_date = "2024-04-05" # Keep this or update to a newer date if needed

# --- VERY IMPORTANT: Enable Deno Compatibility ---
# This tells the Cloudflare Workers runtime to use the Deno runtime layer.
compatibility_flags = [ "nodejs_compat" ]

# --- Secrets ---
# Runtime secrets MUST be configured using the Cloudflare dashboard or Wrangler CLI.
# DO NOT PUT ACTUAL SECRET VALUES HERE.
# These will be available via `Deno.env.get("SECRET_NAME")` in your Worker code
# because you are using the "deno" compatibility flag.
#
# Example commands to set secrets:
# wrangler secret put SUPABASE_URL --env production
# wrangler secret put SUPABASE_ANON_KEY --env production
# wrangler secret put SUPABASE_SERVICE_ROLE_KEY --env production
# (Remove --env production if not using specific environments)
#
# You MUST set these secrets in your Cloudflare Worker settings for the deployed app to work.

# --- Variables ---
# Non-secret environment variables can be defined here.
# Use this for things like environment names (development, staging, production)
[vars]
# EXAMPLE_VAR = "example_value"
# ENVIRONMENT = "production" # Example

# --- Build ---
# A build command is generally NOT required for Deno workers using URL/npm imports.
# [build]
# command = ""

# --- Environments ---
# Example for defining different deployment environments (e.g., production, staging)
[env.production]
name = "veeda-backend-worker" # Explicitly set name for production env
# Add environment-specific secrets or variables via wrangler commands or dashboard.
# Example: wrangler secret put DB_PASSWORD --env production
[env.production.vars]
ENVIRONMENT = "production"

# [env.staging]
# name = "veeda-backend-worker-staging"
# [env.staging.vars]
# ENVIRONMENT = "staging"
# Add staging-specific secrets/vars via wrangler or dashboard
